name: MultiversePE-Core
main: MultiversePE-Core\Main
version: 1.0.0
api: [1.0.0, 1.1.0]

load: STARTUP
authors: [Comedyman937]
description: Multiple world management for PocketMine-MP!

commands:
    multiverse:
        description: "Multiverse Admin Commands!"
        usage: "/multiverse <create|delete|import> [options] <name>"
        aias: [mv, multiv, mverse, multiversepe, mvpe, multivpe, mversepe]
        permission: multiverse.core.multiverse
permissions:
    multiverse.core.multiverse:
        description: "Allows players to use the MultiversePE admin commands!"
        default: op
